In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Materials/customer_behavior_eda.csv")

In [3]:
df

,customer_id,signup_date,region,acquisition_channel,segment,age,annual_income_egp,monthly_spend_egp,orders_last_6m,avg_order_value_egp,satisfaction_score,support_tickets,discount_rate,website_visits_last_30d,is_active,churned
0,CUST-10000,2023-04-13,Mansoura,Web,Bronze,53,"216,154",2209.15,6,334.40,NaN,7,0.36,9,Yes,Yes
1,CUST-10001,NaN,Mansoura,Mobile App,Silver,64,"232,796",2558.02,7,409.97,4.6,3,0.10,18,Yes,No
2,CUST-10002,2023-09-28,Giza,Mobile App,Bronze,38,"137,301",2462.59,9,286.26,3.8,3,0.37,7,Yes,No
3,CUST-10003,2023-04-17,Giza,Mobile App,Bronze,38,80006.0,1817.51,8,250.25,4.1,2,0.22,12,Yes,No
4,CUST-10004,2023-03-13,Alexandria,Mobile App,Gold,44,225943.0,3183.25,6,519.34,4.5,1,0.10,7,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,CUST-10003,2023-04-17,Giza,Mobile App,Bronze,38,80006.0,1817.51,8,250.25,4.1,2,0.22,12,Yes,No
528,CUST-10147,2024-05-17,Asyut,Mobile App,Silver,25,NaN,3062.46,7,368.87,3.4,0,0.17,18,Yes,No
529,CUST-10453,2025-02-21,Cairo,Mobile App,Platinum,35,"215,520",1779.16,7,208.04,2.1,2,0.54,13,Yes,No
530,CUST-10316,2024-08-09,Giza,Call Center,Silver,47,"180,421",3898.60,4,1105.79,3.7,4,0.32,15,Yes,No
531,CUST-10090,2023-09-09,Asyut,Web,Bronze,23,220867.0,2126.50,4,469.81,2.9,3,0.17,14,Yes,Yes

In [4]:
df.head()

,customer_id,signup_date,region,acquisition_channel,segment,age,annual_income_egp,monthly_spend_egp,orders_last_6m,avg_order_value_egp,satisfaction_score,support_tickets,discount_rate,website_visits_last_30d,is_active,churned
0,CUST-10000,2023-04-13,Mansoura,Web,Bronze,53,"216,154",2209.15,6,334.40,NaN,7,0.36,9,Yes,Yes
1,CUST-10001,NaN,Mansoura,Mobile App,Silver,64,"232,796",2558.02,7,409.97,4.6,3,0.10,18,Yes,No
2,CUST-10002,2023-09-28,Giza,Mobile App,Bronze,38,"137,301",2462.59,9,286.26,3.8,3,0.37,7,Yes,No
3,CUST-10003,2023-04-17,Giza,Mobile App,Bronze,38,80006.0,1817.51,8,250.25,4.1,2,0.22,12,Yes,No
4,CUST-10004,2023-03-13,Alexandria,Mobile App,Gold,44,225943.0,3183.25,6,519.34,4.5,1,0.10,7,Yes,No

In [5]:
df.sample(5)

,customer_id,signup_date,region,acquisition_channel,segment,age,annual_income_egp,monthly_spend_egp,orders_last_6m,avg_order_value_egp,satisfaction_score,support_tickets,discount_rate,website_visits_last_30d,is_active,churned
415,CUST-10415,2024-01-28,Cairo,Mobile App,Bronze,44,"106,458",2569.76,6,372.72,3.7,1,0.46,10,Yes,Yes
256,CUST-10256,2025-02-05,Giza,Call Center,Bronze,18,"109,552",2214.89,4,541.05,4.0,2,0.34,16,Yes,Yes
471,CUST-10471,2023-04-16,Cairo,Web,Silver,37,39821.0,2592.70,10,236.30,3.5,1,0.04,13,Yes,No
342,CUST-10342,2024-10-01,Giza,Web,Gold,41,210769.0,1071.67,5,187.30,3.7,1,0.41,10,Yes,No
526,CUST-10050,2023-01-21,Alexandria,Web,Silver,41,"254,713",1849.42,5,417.47,4.0,2,0.06,16,No,No

In [6]:
df.shape

(532, 16)

In [7]:
df.index

RangeIndex(start=0, stop=532, step=1)

In [8]:
df.columns.tolist()

['customer_id',
 'signup_date',
 'region',
 'acquisition_channel',
 'segment',
 'age',
 'annual_income_egp',
 'monthly_spend_egp',
 'orders_last_6m',
 'avg_order_value_egp',
 'satisfaction_score',
 'support_tickets',
 'discount_rate',
 'website_visits_last_30d',
 'is_active',
 'churned']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532 entries, 0 to 531
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              532 non-null    object
 1   signup_date              522 non-null    object
 2   region                   517 non-null    object
 3   acquisition_channel      532 non-null    object
 4   segment                  532 non-null    object
 5   age                      532 non-null    int64
 6   annual_income_egp        500 non-null    object
 7   monthly_spend_egp        532 non-null    float64
 8   orders_last_6m           532 non-null    int64
 9   avg_order_value_egp      512 non-null    float64
 10  satisfaction_score       506 non-null    float64
 11  support_tickets          532 non-null    int64
 12  discount_rate            532 non-null    float64
 13  website_visits_last_30d  532 non-null    int64
 14  is_active                532 non-null    object
 15  churned                  532 non-null    object
dtypes: float64(4), int64(4), object(8)
memory usage: 66.6+ KB

In [10]:
df.dtypes

customer_id                 object
signup_date                 object
region                      object
acquisition_channel         object
segment                     object
age                          int64
annual_income_egp           object
monthly_spend_egp          float64
orders_last_6m               int64
avg_order_value_egp        float64
satisfaction_score         float64
support_tickets              int64
discount_rate              float64
website_visits_last_30d      int64
is_active                   object
churned                     object
dtype: object

In [11]:
cleaned_df = df.copy()

In [12]:
cleaned_df['signup_date'] = pd.to_datetime(cleaned_df['signup_date'])

In [13]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532 entries, 0 to 531
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              532 non-null    object
 1   signup_date              522 non-null    datetime64[ns]
 2   region                   517 non-null    object
 3   acquisition_channel      532 non-null    object
 4   segment                  532 non-null    object
 5   age                      532 non-null    int64
 6   annual_income_egp        500 non-null    object
 7   monthly_spend_egp        532 non-null    float64
 8   orders_last_6m           532 non-null    int64
 9   avg_order_value_egp      512 non-null    float64
 10  satisfaction_score       506 non-null    float64
 11  support_tickets          532 non-null    int64
 12  discount_rate            532 non-null    float64
 13  website_visits_last_30d  532 non-null    int64
 14  is_active                532 non-null    object
 15  churned                  532 non-null    object
dtypes: datetime64[ns](1), float64(4), int64(4), object(7)
memory usage: 66.6+ KB

In [14]:
cleaned_df['annual_income_egp'] = pd.to_numeric(cleaned_df['annual_income_egp'], errors='coerce') # ignore anything you don't know how to convert

In [15]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532 entries, 0 to 531
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              532 non-null    object
 1   signup_date              522 non-null    datetime64[ns]
 2   region                   517 non-null    object
 3   acquisition_channel      532 non-null    object
 4   segment                  532 non-null    object
 5   age                      532 non-null    int64
 6   annual_income_egp        109 non-null    float64
 7   monthly_spend_egp        532 non-null    float64
 8   orders_last_6m           532 non-null    int64
 9   avg_order_value_egp      512 non-null    float64
 10  satisfaction_score       506 non-null    float64
 11  support_tickets          532 non-null    int64
 12  discount_rate            532 non-null    float64
 13  website_visits_last_30d  532 non-null    int64
 14  is_active                532 non-null    object
 15  churned                  532 non-null    object
dtypes: datetime64[ns](1), float64(5), int64(4), object(6)
memory usage: 66.6+ KB

In [16]:
cleaned_data = df.copy()

In [17]:
cleaned_data['annual_income_egp'] = cleaned_data['annual_income_egp'].str.replace(',', '')

In [18]:
cleaned_data['annual_income_egp'] = pd.to_numeric(cleaned_data['annual_income_egp'])

In [19]:
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 532 entries, 0 to 531
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              532 non-null    object
 1   signup_date              522 non-null    object
 2   region                   517 non-null    object
 3   acquisition_channel      532 non-null    object
 4   segment                  532 non-null    object
 5   age                      532 non-null    int64
 6   annual_income_egp        500 non-null    float64
 7   monthly_spend_egp        532 non-null    float64
 8   orders_last_6m           532 non-null    int64
 9   avg_order_value_egp      512 non-null    float64
 10  satisfaction_score       506 non-null    float64
 11  support_tickets          532 non-null    int64
 12  discount_rate            532 non-null    float64
 13  website_visits_last_30d  532 non-null    int64
 14  is_active                532 non-null    object
 15  churned                  532 non-null    object
dtypes: float64(5), int64(4), object(7)
memory usage: 66.6+ KB

In [20]:
cleaned_data['signup_date'] = pd.to_datetime(cleaned_data['signup_date'])

In [21]:
cleaned_data.describe()

,signup_date,age,annual_income_egp,monthly_spend_egp,orders_last_6m,avg_order_value_egp,satisfaction_score,support_tickets,discount_rate,website_visits_last_30d
count,522,532.000000,500.000000,532.000000,532.000000,512.000000,506.000000,532.000000,532.000000,532.000000
mean,2024-02-05 12:00:00,35.857143,185001.576000,2366.084098,6.830827,407.111152,3.573123,1.714286,0.244229,14.637218
min,2023-01-02 00:00:00,18.000000,35000.000000,120.000000,1.000000,50.000000,1.000000,0.000000,0.010000,3.000000
25%,2023-07-09 00:00:00,28.000000,144168.000000,1672.982500,5.000000,220.942500,3.000000,1.000000,0.150000,12.000000
50%,2024-02-04 12:00:00,35.000000,186604.500000,2289.185000,7.000000,329.805000,3.600000,2.000000,0.230000,14.000000
75%,2024-09-09 18:00:00,44.000000,225348.250000,2831.912500,8.000000,484.792500,4.200000,2.000000,0.322500,17.000000
max,2025-03-10 00:00:00,71.000000,391932.000000,27000.000000,17.000000,3227.730000,5.000000,7.000000,0.700000,104.000000
std,NaN,10.861319,66614.747703,1767.899004,2.670468,331.344664,0.844733,1.344985,0.138100,7.065071

In [22]:
cleaned_data.describe(include='object')

       customer_id region acquisition_channel segment is_active churned
count          532    517                 532     532       532     532
unique         520      7                   5       4         2       2
top     CUST-10082  Cairo                 Web  Bronze       Yes      No
freq             2    128                 211     228       413     392

In [23]:
cleaned_data.describe(percentiles=[0.01, 0.1, 0.3, 0.9])

,signup_date,age,annual_income_egp,monthly_spend_egp,orders_last_6m,avg_order_value_egp,satisfaction_score,support_tickets,discount_rate,website_visits_last_30d
count,522,532.000000,500.000000,532.000000,532.000000,512.000000,506.000000,532.000000,532.000000,532.000000
mean,2024-02-05 12:00:00,35.857143,185001.576000,2366.084098,6.830827,407.111152,3.573123,1.714286,0.244229,14.637218
min,2023-01-02 00:00:00,18.000000,35000.000000,120.000000,1.000000,50.000000,1.000000,0.000000,0.010000,3.000000
1%,2023-01-10 01:12:00,18.000000,35000.000000,348.259200,2.000000,50.000000,1.405000,0.000000,0.020000,6.000000
10%,2023-03-27 00:00:00,22.000000,94444.000000,1108.777000,3.000000,145.451000,2.500000,0.000000,0.070000,9.100000
30%,2023-08-15 21:36:00,29.000000,154632.700000,1811.504000,5.000000,238.985000,3.150000,1.000000,0.160000,12.000000
50%,2024-02-04 12:00:00,35.000000,186604.500000,2289.185000,7.000000,329.805000,3.600000,2.000000,0.230000,14.000000
90%,2024-12-27 00:00:00,50.000000,270011.600000,3453.058000,10.000000,727.338000,4.700000,3.000000,0.430000,19.000000
max,2025-03-10 00:00:00,71.000000,391932.000000,27000.000000,17.000000,3227.730000,5.000000,7.000000,0.700000,104.000000
std,NaN,10.861319,66614.747703,1767.899004,2.670468,331.344664,0.844733,1.344985,0.138100,7.065071

In [24]:
cleaned_data.isna().sum().sort_values(ascending=False) # indicates where the missing values are

annual_income_egp          32
satisfaction_score         26
avg_order_value_egp        20
region                     15
signup_date                10
segment                     0
acquisition_channel         0
customer_id                 0
monthly_spend_egp           0
age                         0
orders_last_6m              0
support_tickets             0
discount_rate               0
website_visits_last_30d     0
is_active                   0
churned                     0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(12)

In [26]:
dropped_df = cleaned_data.drop_duplicates()

In [27]:
dropped_df

,customer_id,signup_date,region,acquisition_channel,segment,age,annual_income_egp,monthly_spend_egp,orders_last_6m,avg_order_value_egp,satisfaction_score,support_tickets,discount_rate,website_visits_last_30d,is_active,churned
0,CUST-10000,2023-04-13,Mansoura,Web,Bronze,53,216154.0,2209.15,6,334.40,NaN,7,0.36,9,Yes,Yes
1,CUST-10001,NaT,Mansoura,Mobile App,Silver,64,232796.0,2558.02,7,409.97,4.6,3,0.10,18,Yes,No
2,CUST-10002,2023-09-28,Giza,Mobile App,Bronze,38,137301.0,2462.59,9,286.26,3.8,3,0.37,7,Yes,No
3,CUST-10003,2023-04-17,Giza,Mobile App,Bronze,38,80006.0,1817.51,8,250.25,4.1,2,0.22,12,Yes,No
4,CUST-10004,2023-03-13,Alexandria,Mobile App,Gold,44,225943.0,3183.25,6,519.34,4.5,1,0.10,7,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,CUST-10515,2023-04-04,cairo,Web,Gold,24,269991.0,1603.13,10,NaN,2.6,1,0.29,15,Yes,Yes
516,CUST-10516,2025-01-19,NaN,Web,Gold,41,177257.0,1165.33,10,106.63,2.2,2,0.28,14,Yes,No
517,CUST-10517,2024-03-28,Giza,Mobile App,Silver,18,305544.0,1314.46,7,175.24,3.9,2,0.13,11,Yes,No
518,CUST-10518,2023-07-23,Mansoura,Mobile App,Silver,27,173379.0,1955.36,2,948.95,2.4,0,0.01,13,Yes,No
519,CUST-10519,2023-08-06,Alexandria,Mobile App,Bronze,52,227087.0,1660.15,4,355.16,NaN,5,0.52,10,Yes,No

In [28]:
dropped_df['region'].value_counts()

region
Cairo         126
Giza          112
Alexandria    100
Mansoura       82
Asyut          67
 cairo         10
GIZA            8
Name: count, dtype: int64

In [30]:
dropped_df['region'] = dropped_df['region'].str.strip().str.capitalize()

C:\Users\DELL\AppData\Local\Temp\ipykernel_5840\562881173.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropped_df['region'] = dropped_df['region'].str.strip().str.capitalize()

In [31]:
dropped_df['region'].value_counts()

region
Cairo         136
Giza          120
Alexandria    100
Mansoura       82
Asyut          67
Name: count, dtype: int64

In [32]:
dropped_df['acquisition_channel'].value_counts()

acquisition_channel
Web            206
Mobile App     196
Branch          64
Call Center     47
mobile app       7
Name: count, dtype: int64

In [33]:
dropped_df['acquisition_channel'] = dropped_df['acquisition_channel'].str.strip().str.title()

C:\Users\DELL\AppData\Local\Temp\ipykernel_5840\611183197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dropped_df['acquisition_channel'] = dropped_df['acquisition_channel'].str.strip().str.title()

In [34]:
dropped_df['acquisition_channel'].value_counts()

acquisition_channel
Web            206
Mobile App     203
Branch          64
Call Center     47
Name: count, dtype: int64

In [35]:
dropped_df['segment'].value_counts()

segment
Bronze      225
Silver      162
Gold         96
Platinum     37
Name: count, dtype: int64

In [36]:
dropped_df.corr(numeric_only=True)

,age,annual_income_egp,monthly_spend_egp,orders_last_6m,avg_order_value_egp,satisfaction_score,support_tickets,discount_rate,website_visits_last_30d
age,1.000000,0.068880,0.026864,0.046994,-0.021976,-0.007203,0.034514,-0.074151,0.054845
annual_income_egp,0.068880,1.000000,-0.093741,-0.003105,-0.031982,-0.024226,-0.035207,-0.016274,0.022387
monthly_spend_egp,0.026864,-0.093741,1.000000,-0.075666,0.250417,0.023996,0.081402,-0.082441,0.008094
orders_last_6m,0.046994,-0.003105,-0.075666,1.000000,-0.610715,0.034695,-0.022723,-0.030286,0.014454
avg_order_value_egp,-0.021976,-0.031982,0.250417,-0.610715,1.000000,-0.020394,-0.038446,-0.037035,-0.024021
satisfaction_score,-0.007203,-0.024226,0.023996,0.034695,-0.020394,1.000000,0.105443,-0.014686,-0.057676
support_tickets,0.034514,-0.035207,0.081402,-0.022723,-0.038446,0.105443,1.000000,0.044757,-0.014602
discount_rate,-0.074151,-0.016274,-0.082441,-0.030286,-0.037035,-0.014686,0.044757,1.000000,-0.054794
website_visits_last_30d,0.054845,0.022387,0.008094,0.014454,-0.024021,-0.057676,-0.014602,-0.054794,1.000000

In [37]:
dropped_df.groupby('region')['annual_income_egp'].mean()

region
Alexandria    181129.204301
Asyut         185529.380952
Cairo         180120.984733
Giza          188151.819820
Mansoura      192023.493506
Name: annual_income_egp, dtype: float64

In [38]:
dropped_df.groupby('region').agg({'annual_income_egp': ['mean', 'max', 'min', 'sum']})

           annual_income_egp
                        mean       max      min         sum
region
Alexandria     181129.204301  301593.0  36508.0  16845016.0
Asyut          185529.380952  307747.0  35000.0  11688351.0
Cairo          180120.984733  370018.0  35000.0  23595849.0
Giza           188151.819820  391932.0  35000.0  20884852.0
Mansoura       192023.493506  339504.0  35000.0  14785809.0

In [39]:
q1, q3 = dropped_df['age'].quantile([0.25, 0.75])
iqr = q3 - q1
lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr

print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Lower Bound:", lower)
print("Upper Bound:", upper)
dropped_df[(dropped_df['age'] < lower) | (dropped_df['age'] > upper)]

Q1: 28.0
Q3: 44.0
IQR: 16.0
Lower Bound: 4.0
Upper Bound: 68.0

,customer_id,signup_date,region,acquisition_channel,segment,age,annual_income_egp,monthly_spend_egp,orders_last_6m,avg_order_value_egp,satisfaction_score,support_tickets,discount_rate,website_visits_last_30d,is_active,churned
365,CUST-10365,2024-03-28,Alexandria,Call Center,Bronze,69,301593.0,1374.86,8,138.34,3.1,1,0.18,20,Yes,No
438,CUST-10438,2025-03-10,Mansoura,Branch,Bronze,71,180175.0,2371.64,7,314.17,NaN,0,0.33,21,Yes,Yes

In [40]:
(((dropped_df['age'] - dropped_df['age'].mean()) / dropped_df['age'].std()).abs() > 3).sum()

np.int64(2)

In [41]:
dropped_df.to_csv('cleaned_customer_behavior.csv')