In [1]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('../Materials/city_sustainability_geospatial.csv')

In [2]:
df

,city,country,continent,iso_alpha3,latitude,longitude,population_millions,avg_temp_c,co2_tons_per_capita,renewable_energy_share,air_quality_index,traffic_congestion_index,is_coastal
0,City_1,United States,North America,USA,30.2176,-92.4343,7.55,26.7,7.70,18.3,79.7,75.6,No
1,City_2,Canada,North America,CAN,52.3668,-75.3981,11.35,21.8,9.14,37.1,45.4,60.4,Yes
2,City_3,Saudi Arabia,Asia,SAU,26.9573,42.2140,7.27,27.5,1.22,25.2,36.5,41.5,No
3,City_4,South Africa,Africa,ZAF,-29.1878,27.4098,8.94,29.8,5.74,34.5,58.4,98.0,No
4,City_5,South Africa,Africa,ZAF,-28.7371,18.8952,8.89,10.5,1.45,23.1,45.0,83.3,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,City_296,South Africa,Africa,ZAF,-22.4764,18.3267,8.67,13.2,6.13,29.9,67.9,92.2,Yes
296,City_297,Egypt,Africa,EGY,31.1816,28.4269,6.25,27.8,3.93,38.6,70.8,68.6,No
297,City_298,Brazil,South America,BRA,-12.3863,-57.7887,13.94,16.2,8.57,30.7,71.9,65.9,No
298,City_299,Canada,North America,CAN,45.4609,-61.0468,9.09,27.2,5.08,8.4,95.5,79.3,Yes
299,City_300,China,Asia,CHN,23.9269,119.1980,14.63,7.2,6.71,20.3,65.8,88.1,No

In [3]:
#population_vs_co2 = px.scatter(df, x="population_millions", y="co2_tons_per_capita")
population_vs_co2 = px.scatter(df, x="population_millions", y="co2_tons_per_capita", color='continent', size='avg_temp_c', hover_name='city',
hover_data=['renewable_energy_share', 'air_quality_index'])
population_vs_co2.show()

In [4]:
continent_vs_population_data = df.groupby('continent')['population_millions'].sum().reset_index()
continent_vs_population_data

       continent  population_millions
0         Africa               471.79
1           Asia               581.91
2         Europe               354.70
3  North America               459.96
4  South America               229.72

In [5]:
continent_vs_population = px.bar(continent_vs_population_data, x='continent', y='population_millions')
continent_vs_population.show()

In [6]:
pop_hist = px.histogram(df, x='population_millions', nbins=40, color='continent', marginal='box')
pop_hist.show()

In [7]:
continent_co2 = px.box(df, x='continent', y='co2_tons_per_capita', color='continent', points='all')
continent_co2.show()

In [8]:
top_population_cities = df.nlargest(20, 'population_millions') 
top_population_cities

,city,country,continent,iso_alpha3,latitude,longitude,population_millions,avg_temp_c,co2_tons_per_capita,renewable_energy_share,air_quality_index,traffic_congestion_index,is_coastal
190,City_191,Egypt,Africa,EGY,25.7837,26.4924,14.98,11.2,6.66,25.6,56.2,100.0,No
236,City_237,Egypt,Africa,EGY,30.2793,34.6698,14.95,7.2,2.31,13.9,67.5,96.1,No
115,City_116,China,Asia,CHN,21.0418,108.1356,14.91,9.3,5.74,19.5,77.6,98.2,No
227,City_228,Canada,North America,CAN,53.4209,-105.2695,14.88,19.1,3.85,42.6,54.1,100.0,No
239,City_240,Canada,North America,CAN,52.7816,-76.4740,14.88,26.7,9.99,39.2,82.6,100.0,No
89,City_90,Canada,North America,CAN,58.4596,-89.2589,14.80,26.6,7.51,23.8,75.9,94.2,Yes
5,City_6,Egypt,Africa,EGY,27.9390,31.9497,14.70,22.3,4.85,42.4,61.6,97.7,No
299,City_300,China,Asia,CHN,23.9269,119.1980,14.63,7.2,6.71,20.3,65.8,88.1,No
22,City_23,Canada,North America,CAN,49.0577,-92.8957,14.56,26.3,6.27,34.5,51.1,89.4,No
65,City_66,Saudi Arabia,Asia,SAU,28.9270,35.1114,14.52,19.8,4.04,29.1,66.9,100.0,No
272,City_273,India,Asia,IND,16.6175,81.2494,14.38,7.0,4.60,30.5,63.7,83.4,No
149,City_150,Germany,Europe,DEU,50.8738,14.3242,14.33,7.0,5.51,45.9,81.1,51.8,Yes
15,City_16,India,Asia,IND,25.3262,74.5082,14.29,8.5,5.96,32.3,72.2,100.0,No
248,City_249,Brazil,South America,BRA,-18.1568,-42.9052,14.24,13.7,2.96,30.3,96.7,100.0,Yes
199,City_200,Egypt,Africa,EGY,22.3739,33.3605,14.06,19.6,2.94,28.0,64.5,67.0,Yes
68,City_69,United States,North America,USA,40.8870,-78.3582,14.00,12.2,5.72,22.7,86.9,48.8,Yes
176,City_177,Egypt,Africa,EGY,24.2216,25.0009,13.97,25.1,9.61,43.6,65.5,100.0,No
297,City_298,Brazil,South America,BRA,-12.3863,-57.7887,13.94,16.2,8.57,30.7,71.9,65.9,No
234,City_235,Brazil,South America,BRA,-24.2327,-62.7532,13.85,29.0,4.64,36.9,47.2,90.0,No
222,City_223,South Africa,Africa,ZAF,-31.0806,19.8321,13.77,28.4,6.19,25.9,74.8,89.0,Yes

In [9]:
top_population_cities_costal = top_population_cities[top_population_cities['is_coastal'] == 'Yes']
top_population_cities_costal

,city,country,continent,iso_alpha3,latitude,longitude,population_millions,avg_temp_c,co2_tons_per_capita,renewable_energy_share,air_quality_index,traffic_congestion_index,is_coastal
89,City_90,Canada,North America,CAN,58.4596,-89.2589,14.80,26.6,7.51,23.8,75.9,94.2,Yes
149,City_150,Germany,Europe,DEU,50.8738,14.3242,14.33,7.0,5.51,45.9,81.1,51.8,Yes
248,City_249,Brazil,South America,BRA,-18.1568,-42.9052,14.24,13.7,2.96,30.3,96.7,100.0,Yes
199,City_200,Egypt,Africa,EGY,22.3739,33.3605,14.06,19.6,2.94,28.0,64.5,67.0,Yes
68,City_69,United States,North America,USA,40.8870,-78.3582,14.00,12.2,5.72,22.7,86.9,48.8,Yes
222,City_223,South Africa,Africa,ZAF,-31.0806,19.8321,13.77,28.4,6.19,25.9,74.8,89.0,Yes

In [11]:
coastal_population = px.pie(top_population_cities, values='population_millions', names='is_coastal', hole=0.7)
coastal_population.show()

In [16]:
fig = px.scatter_geo(df, lat='latitude', lon='longitude', color='continent', size='population_millions', hover_name='city'
                     , projection='natural earth', title='Global City Population Distribution', hover_data={'population_millions': True,
                                                                                                            'latitude': False, 'longitude': False,
                                                                                                            'continent': True, 'country': True})
fig.show()

In [18]:
avg_co2_per_country = df.groupby('country')['co2_tons_per_capita'].mean().reset_index()
avg_co2_per_iso = df.groupby('iso_alpha3')['co2_tons_per_capita'].mean().reset_index()
avg_co2_per_country['iso_alpha3'] = avg_co2_per_iso['iso_alpha3']
avg_co2_per_country

          country  co2_tons_per_capita iso_alpha3
0          Brazil             5.004688        BRA
1          Canada             7.395429        CAN
2           China             5.072143        CHN
3           Egypt             4.478529        DEU
4         Germany             4.702258        EGY
5           India             5.621176        GBR
6    Saudi Arabia             5.087308        IND
7    South Africa             4.510000        SAU
8  United Kingdom             4.726087        USA
9   United States             7.083200        ZAF

In [19]:
country_stats = df.groupby(['country', 'iso_alpha3'], as_index=False).agg(avg_co2=('co2_tons_per_capita', 'mean'),
                                                                         avg_temp=('avg_temp_c', 'mean'))
country_stats

          country iso_alpha3   avg_co2   avg_temp
0          Brazil        BRA  5.004688  17.015625
1          Canada        CAN  7.395429  19.905714
2           China        CHN  5.072143  16.321429
3           Egypt        EGY  4.478529  18.700000
4         Germany        DEU  4.702258  16.500000
5           India        IND  5.621176  16.723529
6    Saudi Arabia        SAU  5.087308  18.346154
7    South Africa        ZAF  4.510000  19.325000
8  United Kingdom        GBR  4.726087  17.921739
9   United States        USA  7.083200  18.284000

In [21]:
px.choropleth(
    country_stats,
    locations='iso_alpha3',
    color='avg_co2',
    hover_name='country',
    hover_data=['avg_temp'],
    color_continuous_scale='haline',
    projection='natural earth'
)